"""make_calibre_nullable_in_productions

Revision ID: 418e5bb36fb5
Revises: 5d3c4087733d
Create Date: 2026-03-22 22:09:25.055945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418e5bb36fb5'
down_revision: Union[str, None] = '5d3c4087733d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lettres_credit', sa.Column('numero_serie', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_lettres_credit_numero_serie'), 'lettres_credit', ['numero_serie'], unique=False)
    op.alter_column('productions', 'calibre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productions', 'calibre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_lettres_credit_numero_serie'), table_name='lettres_credit')
    op.drop_column('lettres_credit', 'numero_serie')
    # ### end Alembic commands ###
