"""add_transformation_and_missing_fields

Revision ID: 5d3c4087733d
Revises: fix_caisse_view_constraints
Create Date: 2026-03-22 21:21:54.433296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3c4087733d'
down_revision: Union[str, None] = 'fix_caisse_view_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformations',
    sa.Column('id_transformation', sa.Integer(), nullable=False),
    sa.Column('date_transformation', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_transformation')
    )
    op.create_index(op.f('ix_transformations_id_transformation'), 'transformations', ['id_transformation'], unique=False)
    op.create_table('transformation_lignes',
    sa.Column('id_ligne', sa.Integer(), nullable=False),
    sa.Column('id_transformation', sa.Integer(), nullable=False),
    sa.Column('id_produit', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type_ligne', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_produit'], ['produits.id_produit'], ),
    sa.ForeignKeyConstraint(['id_transformation'], ['transformations.id_transformation'], ),
    sa.PrimaryKeyConstraint('id_ligne')
    )
    op.create_index(op.f('ix_transformation_lignes_id_ligne'), 'transformation_lignes', ['id_ligne'], unique=False)
    op.create_index(op.f('ix_transformation_lignes_id_produit'), 'transformation_lignes', ['id_produit'], unique=False)
    op.create_index(op.f('ix_transformation_lignes_id_transformation'), 'transformation_lignes', ['id_transformation'], unique=False)
    op.create_index(op.f('ix_transformation_lignes_type_ligne'), 'transformation_lignes', ['type_ligne'], unique=False)
    op.drop_index('idx_caisse_id_charge', table_name='caisse')
    op.drop_index('idx_caisse_id_paiement', table_name='caisse')
    op.create_index(op.f('ix_caisse_id_charge'), 'caisse', ['id_charge'], unique=False)
    op.create_index(op.f('ix_caisse_id_paiement'), 'caisse', ['id_paiement'], unique=False)
    op.drop_index('idx_cession_lc_date', table_name='cessions_lc')
    op.create_index(op.f('ix_cessions_lc_date_cession'), 'cessions_lc', ['date_cession'], unique=False)
    op.create_index(op.f('ix_cessions_lc_id_cession'), 'cessions_lc', ['id_cession'], unique=False)
    op.create_index(op.f('ix_cessions_lc_id_lc'), 'cessions_lc', ['id_lc'], unique=False)
    op.drop_constraint('fk_cession_lc', 'cessions_lc', type_='foreignkey')
    op.create_foreign_key(None, 'cessions_lc', 'lettres_credit', ['id_lc'], ['id_lc'])
    op.add_column('charges', sa.Column('id_compte', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'charges', 'comptes_bancaires', ['id_compte'], ['id_compte'])
    op.drop_index('idx_lc_date_dispo', table_name='lettres_credit')
    op.drop_index('idx_lc_numero_ref', table_name='lettres_credit')
    op.drop_index('idx_lc_statut', table_name='lettres_credit')
    op.drop_constraint('uq_lc_numero_reference', 'lettres_credit', type_='unique')
    op.create_index(op.f('ix_lettres_credit_date_disponibilite'), 'lettres_credit', ['date_disponibilite'], unique=False)
    op.create_index(op.f('ix_lettres_credit_id_client'), 'lettres_credit', ['id_client'], unique=False)
    op.create_index(op.f('ix_lettres_credit_id_fournisseur'), 'lettres_credit', ['id_fournisseur'], unique=False)
    op.create_index(op.f('ix_lettres_credit_id_lc'), 'lettres_credit', ['id_lc'], unique=False)
    op.create_index(op.f('ix_lettres_credit_numero_reference'), 'lettres_credit', ['numero_reference'], unique=True)
    op.create_index(op.f('ix_lettres_credit_statut'), 'lettres_credit', ['statut'], unique=False)
    op.create_index(op.f('ix_lettres_credit_type_detenteur'), 'lettres_credit', ['type_detenteur'], unique=False)
    op.add_column('mouvements_bancaires', sa.Column('id_charge', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mouvements_bancaires', 'charges', ['id_charge'], ['id_charge'])
    op.alter_column('paiements', 'date_paiement',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date du paiement',
               existing_nullable=False)
    op.alter_column('paiements', 'montant',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Montant du paiement',
               existing_nullable=False)
    op.alter_column('paiements', 'type_paiement',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type de paiement (cash, cheque, virement, etc.)',
               existing_nullable=False)
    op.alter_column('paiements', 'numero_cheque',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Numéro du chèque',
               existing_nullable=True)
    op.alter_column('paiements', 'banque',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Banque émettrice du chèque',
               existing_nullable=True)
    op.alter_column('paiements', 'date_encaissement_prevue',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment="Date prévue d'encaissement du chèque",
               existing_nullable=True)
    op.alter_column('paiements', 'date_encaissement_effective',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment="Date effective d'encaissement du chèque",
               existing_nullable=True)
    op.alter_column('paiements', 'statut_cheque',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut du chèque (emis, a_encaisser, encaisse, rejete, annule)',
               existing_nullable=True)
    op.alter_column('paiements', 'motif_rejet',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Motif du rejet si le chèque est rejeté',
               existing_nullable=True)
    op.alter_column('paiements', 'reference_virement',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Référence du virement bancaire',
               existing_nullable=True)
    op.alter_column('paiements', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notes ou commentaires additionnels',
               existing_nullable=True)
    op.alter_column('paiements', 'statut',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut du paiement (valide, en_attente, rejete, annule)',
               existing_nullable=False,
               existing_server_default=sa.text("'valide'::character varying"))
    op.drop_index('idx_paiements_date_paiement', table_name='paiements')
    op.drop_index('idx_paiements_id_lc', table_name='paiements')
    op.drop_index('idx_paiements_id_transaction', table_name='paiements')
    op.drop_index('idx_paiements_numero_cheque', table_name='paiements')
    op.drop_index('idx_paiements_type_paiement', table_name='paiements')
    op.create_index(op.f('ix_paiements_date_paiement'), 'paiements', ['date_paiement'], unique=False)
    op.create_index(op.f('ix_paiements_id_lc'), 'paiements', ['id_lc'], unique=False)
    op.create_index(op.f('ix_paiements_id_paiement'), 'paiements', ['id_paiement'], unique=False)
    op.create_index(op.f('ix_paiements_id_transaction'), 'paiements', ['id_transaction'], unique=False)
    op.create_index(op.f('ix_paiements_numero_cheque'), 'paiements', ['numero_cheque'], unique=False)
    op.create_index(op.f('ix_paiements_type_paiement'), 'paiements', ['type_paiement'], unique=False)
    op.drop_constraint('fk_paiements_transaction', 'paiements', type_='foreignkey')
    op.create_foreign_key(None, 'paiements', 'transactions', ['id_transaction'], ['id_transaction'])
    op.add_column('produits', sa.Column('type_produit', sa.String(length=20), nullable=False))
    op.drop_index('idx_produits_pour_clients', table_name='produits')
    op.drop_index('idx_produits_pour_fournisseurs', table_name='produits')
    op.create_index(op.f('ix_produits_pour_clients'), 'produits', ['pour_clients'], unique=False)
    op.create_index(op.f('ix_produits_pour_fournisseurs'), 'produits', ['pour_fournisseurs'], unique=False)
    op.create_index(op.f('ix_produits_type_produit'), 'produits', ['type_produit'], unique=False)
    op.alter_column('transactions', 'date_echeance',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date limite de paiement',
               existing_nullable=True)
    op.drop_index('idx_transactions_actif', table_name='transactions')
    op.drop_index('idx_transactions_client', table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_date_echeance', table_name='transactions')
    op.drop_index('idx_transactions_fournisseur', table_name='transactions')
    op.drop_index('idx_transactions_id_client', table_name='transactions')
    op.drop_index('idx_transactions_id_fournisseur', table_name='transactions')
    op.drop_index('idx_transactions_id_produit', table_name='transactions')
    op.create_index(op.f('ix_transactions_date_echeance'), 'transactions', ['date_echeance'], unique=False)
    op.create_index(op.f('ix_transactions_id_produit'), 'transactions', ['id_produit'], unique=False)
    op.drop_index('idx_audit_date', table_name='transactions_audit')
    op.drop_index('idx_audit_transaction', table_name='transactions_audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_transaction', 'transactions_audit', ['id_transaction'], unique=False)
    op.create_index('idx_audit_date', 'transactions_audit', ['date_changement'], unique=False)
    op.drop_index(op.f('ix_transactions_id_produit'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date_echeance'), table_name='transactions')
    op.create_index('idx_transactions_id_produit', 'transactions', ['id_produit'], unique=False)
    op.create_index('idx_transactions_id_fournisseur', 'transactions', ['id_fournisseur'], unique=False)
    op.create_index('idx_transactions_id_client', 'transactions', ['id_client'], unique=False)
    op.create_index('idx_transactions_fournisseur', 'transactions', ['id_fournisseur'], unique=False)
    op.create_index('idx_transactions_date_echeance', 'transactions', ['date_echeance'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['date_transaction'], unique=False)
    op.create_index('idx_transactions_client', 'transactions', ['id_client'], unique=False)
    op.create_index('idx_transactions_actif', 'transactions', ['est_actif'], unique=False)
    op.alter_column('transactions', 'date_echeance',
               existing_type=sa.DATE(),
               comment='Date limite de paiement',
               existing_nullable=True)
    op.drop_index(op.f('ix_produits_type_produit'), table_name='produits')
    op.drop_index(op.f('ix_produits_pour_fournisseurs'), table_name='produits')
    op.drop_index(op.f('ix_produits_pour_clients'), table_name='produits')
    op.create_index('idx_produits_pour_fournisseurs', 'produits', ['pour_fournisseurs'], unique=False)
    op.create_index('idx_produits_pour_clients', 'produits', ['pour_clients'], unique=False)
    op.drop_column('produits', 'type_produit')
    op.drop_constraint(None, 'paiements', type_='foreignkey')
    op.create_foreign_key('fk_paiements_transaction', 'paiements', 'transactions', ['id_transaction'], ['id_transaction'], ondelete='CASCADE')
    op.drop_index(op.f('ix_paiements_type_paiement'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_numero_cheque'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id_transaction'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id_paiement'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id_lc'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_date_paiement'), table_name='paiements')
    op.create_index('idx_paiements_type_paiement', 'paiements', ['type_paiement'], unique=False)
    op.create_index('idx_paiements_numero_cheque', 'paiements', ['numero_cheque'], unique=False)
    op.create_index('idx_paiements_id_transaction', 'paiements', ['id_transaction'], unique=False)
    op.create_index('idx_paiements_id_lc', 'paiements', ['id_lc'], unique=False)
    op.create_index('idx_paiements_date_paiement', 'paiements', ['date_paiement'], unique=False)
    op.alter_column('paiements', 'statut',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut du paiement (valide, en_attente, rejete, annule)',
               existing_nullable=False,
               existing_server_default=sa.text("'valide'::character varying"))
    op.alter_column('paiements', 'notes',
               existing_type=sa.TEXT(),
               comment='Notes ou commentaires additionnels',
               existing_nullable=True)
    op.alter_column('paiements', 'reference_virement',
               existing_type=sa.VARCHAR(length=100),
               comment='Référence du virement bancaire',
               existing_nullable=True)
    op.alter_column('paiements', 'motif_rejet',
               existing_type=sa.TEXT(),
               comment='Motif du rejet si le chèque est rejeté',
               existing_nullable=True)
    op.alter_column('paiements', 'statut_cheque',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut du chèque (emis, a_encaisser, encaisse, rejete, annule)',
               existing_nullable=True)
    op.alter_column('paiements', 'date_encaissement_effective',
               existing_type=sa.DATE(),
               comment="Date effective d'encaissement du chèque",
               existing_nullable=True)
    op.alter_column('paiements', 'date_encaissement_prevue',
               existing_type=sa.DATE(),
               comment="Date prévue d'encaissement du chèque",
               existing_nullable=True)
    op.alter_column('paiements', 'banque',
               existing_type=sa.VARCHAR(length=100),
               comment='Banque émettrice du chèque',
               existing_nullable=True)
    op.alter_column('paiements', 'numero_cheque',
               existing_type=sa.VARCHAR(length=50),
               comment='Numéro du chèque',
               existing_nullable=True)
    op.alter_column('paiements', 'type_paiement',
               existing_type=sa.VARCHAR(length=20),
               comment='Type de paiement (cash, cheque, virement, etc.)',
               existing_nullable=False)
    op.alter_column('paiements', 'montant',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Montant du paiement',
               existing_nullable=False)
    op.alter_column('paiements', 'date_paiement',
               existing_type=sa.DATE(),
               comment='Date du paiement',
               existing_nullable=False)
    op.drop_constraint(None, 'mouvements_bancaires', type_='foreignkey')
    op.drop_column('mouvements_bancaires', 'id_charge')
    op.drop_index(op.f('ix_lettres_credit_type_detenteur'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_statut'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_numero_reference'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_id_lc'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_id_fournisseur'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_id_client'), table_name='lettres_credit')
    op.drop_index(op.f('ix_lettres_credit_date_disponibilite'), table_name='lettres_credit')
    op.create_unique_constraint('uq_lc_numero_reference', 'lettres_credit', ['numero_reference'])
    op.create_index('idx_lc_statut', 'lettres_credit', ['statut'], unique=False)
    op.create_index('idx_lc_numero_ref', 'lettres_credit', ['numero_reference'], unique=False)
    op.create_index('idx_lc_date_dispo', 'lettres_credit', ['date_disponibilite'], unique=False)
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_column('charges', 'id_compte')
    op.drop_constraint(None, 'cessions_lc', type_='foreignkey')
    op.create_foreign_key('fk_cession_lc', 'cessions_lc', 'lettres_credit', ['id_lc'], ['id_lc'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cessions_lc_id_lc'), table_name='cessions_lc')
    op.drop_index(op.f('ix_cessions_lc_id_cession'), table_name='cessions_lc')
    op.drop_index(op.f('ix_cessions_lc_date_cession'), table_name='cessions_lc')
    op.create_index('idx_cession_lc_date', 'cessions_lc', ['date_cession'], unique=False)
    op.drop_index(op.f('ix_caisse_id_paiement'), table_name='caisse')
    op.drop_index(op.f('ix_caisse_id_charge'), table_name='caisse')
    op.create_index('idx_caisse_id_paiement', 'caisse', ['id_paiement'], unique=False)
    op.create_index('idx_caisse_id_charge', 'caisse', ['id_charge'], unique=False)
    op.drop_index(op.f('ix_transformation_lignes_type_ligne'), table_name='transformation_lignes')
    op.drop_index(op.f('ix_transformation_lignes_id_transformation'), table_name='transformation_lignes')
    op.drop_index(op.f('ix_transformation_lignes_id_produit'), table_name='transformation_lignes')
    op.drop_index(op.f('ix_transformation_lignes_id_ligne'), table_name='transformation_lignes')
    op.drop_table('transformation_lignes')
    op.drop_index(op.f('ix_transformations_id_transformation'), table_name='transformations')
    op.drop_table('transformations')
    # ### end Alembic commands ###
